{
    "Modified": "2013-05-15T03:25:00",
    "Published": "2012-08-14T22:55:00",
    "access": {
        "authentication": "NONE",
        "complexity": "LOW",
        "vector": "NETWORK"
    },
    "assigner": "cve@mitre.org",
    "capec": [],
    "cvss": 6.4,
    "cvss-time": "2013-05-15T03:25:00",
    "cvss-vector": "AV:N/AC:L/Au:N/C:P/I:N/A:P",
    "cwe": "NVD-CWE-Other",
    "id": "CVE-2012-2135",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "PARTIAL",
        "integrity": "NONE"
    },
    "last-modified": "2013-05-15T03:25:00",
    "references": [
        "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389",
        "http://bugs.python.org/issue14579",
        "http://secunia.com/advisories/51087",
        "http://secunia.com/advisories/51089",
        "http://www.openwall.com/lists/oss-security/2012/04/25/2",
        "http://www.openwall.com/lists/oss-security/2012/04/25/4",
        "http://www.ubuntu.com/usn/USN-1615-1",
        "http://www.ubuntu.com/usn/USN-1616-1"
    ],
    "refmap": {
        "misc": [
            "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389",
            "http://bugs.python.org/issue14579"
        ],
        "mlist": [
            "[oss-security] 20120425 CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
            "[oss-security] 20120425 Re: CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated"
        ],
        "secunia": [
            "51087",
            "51089"
        ],
        "ubuntu": [
            "USN-1615-1",
            "USN-1616-1"
        ]
    },
    "summary": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.1.1:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.1.1:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.1.2:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.1.2:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.1.5:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.1.5:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.3:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.2.3:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.2150:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.2.2150:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.3:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3:beta2:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.3:beta2:*:*:*:*:*:*"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [],
    "vulnerable_product": [
        "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.1.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.1.2:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.1.5:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.2.3:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.2.2150:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.3:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.3:beta2:*:*:*:*:*:*"
    ]
}