{
    "Modified": "2019-10-25T11:53:00",
    "Published": "2010-10-19T20:00:00",
    "access": {
        "authentication": "NONE",
        "complexity": "MEDIUM",
        "vector": "NETWORK"
    },
    "assigner": "cve@mitre.org",
    "capec": [
        {
            "id": "26",
            "name": "Leveraging Race Conditions",
            "prerequisites": "A resource is accessed/modified concurrently by multiple processes such that a race condition exists. The adversary has the ability to modify the resource.",
            "related_weakness": [
                "362",
                "363",
                "366",
                "368",
                "370",
                "662",
                "665",
                "667",
                "689"
            ],
            "solutions": "Use safe libraries to access resources such as files. Be aware that improper use of access function calls such as chown(), tempfile(), chmod(), etc. can cause a race condition. Use synchronization to control the flow of execution. Use static analysis tools to find race conditions. Pay attention to concurrency problems related to the access of resources.",
            "summary": "The adversary targets a race condition occurring when multiple processes access and manipulate the same resource concurrently, and the outcome of the execution depends on the particular order in which the access takes place. The adversary can leverage a race condition by \"running the race\", modifying the resource and modifying the normal execution flow. For instance, a race condition can occur while accessing a file: the adversary can trick the system by replacing the original file with his version and cause the system to read the malicious file."
        },
        {
            "id": "29",
            "name": "Leveraging Time-of-Check and Time-of-Use (TOCTOU) Race Conditions",
            "prerequisites": "A resource is access/modified concurrently by multiple processes. The adversary is able to modify resource. A race condition exists while accessing a resource.",
            "related_weakness": [
                "362",
                "366",
                "367",
                "368",
                "370",
                "662",
                "663",
                "665",
                "691"
            ],
            "solutions": "Use safe libraries to access resources such as files. Be aware that improper use of access function calls such as chown(), tempfile(), chmod(), etc. can cause a race condition. Use synchronization to control the flow of execution. Use static analysis tools to find race conditions. Pay attention to concurrency problems related to the access of resources.",
            "summary": "This attack targets a race condition occurring between the time of check (state) for a resource and the time of use of a resource. A typical example is file access. The adversary can leverage a file access race condition by \"running the race\", meaning that they would modify the resource between the first time the target program accesses the file and the time the target program uses the file. During that period of time, the adversary could replace or modify the file, causing the application to behave unexpectedly."
        }
    ],
    "cvss": 4.3,
    "cvss-time": "2019-10-25T11:53:00",
    "cvss-vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
    "cwe": "CWE-362",
    "id": "CVE-2010-3493",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "NONE",
        "integrity": "NONE"
    },
    "last-modified": "2019-10-25T11:53:00",
    "oval": [
        {
            "accepted": "2013-11-14T10:21:28.623-05:00",
            "class": "vulnerability",
            "contributors": [
                {
                    "name": "SecPod Team",
                    "organization": "SecPod Technologies"
                },
                {
                    "name": "Shane Shaffer",
                    "organization": "G2, Inc."
                },
                {
                    "name": "Shane Shaffer",
                    "organization": "G2, Inc."
                },
                {
                    "name": "Maria Kedovskaya",
                    "organization": "ALTX-SOFT"
                },
                {
                    "name": "Maria Kedovskaya",
                    "organization": "ALTX-SOFT"
                },
                {
                    "name": "Maria Kedovskaya",
                    "organization": "ALTX-SOFT"
                },
                {
                    "name": "Maria Kedovskaya",
                    "organization": "ALTX-SOFT"
                }
            ],
            "definition_extensions": [
                {
                    "comment": "Python is installed",
                    "oval": "oval:org.mitre.oval:def:11791"
                }
            ],
            "description": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492.",
            "family": "windows",
            "id": "oval:org.mitre.oval:def:12210",
            "status": "accepted",
            "submitted": "2010-11-18T10:50:19",
            "title": "Vulnerability in smtpd module in Python 2.6, 2.7, 3.1 and 3.2 alpha",
            "version": "85"
        }
    ],
    "redhat": {
        "rpms": [
            "python-0:2.3.4-14.10.el4",
            "python-debuginfo-0:2.3.4-14.10.el4",
            "python-devel-0:2.3.4-14.10.el4",
            "python-docs-0:2.3.4-14.10.el4",
            "python-tools-0:2.3.4-14.10.el4",
            "tkinter-0:2.3.4-14.10.el4",
            "python-0:2.4.3-44.el5",
            "python-debuginfo-0:2.4.3-44.el5",
            "python-devel-0:2.4.3-44.el5",
            "python-libs-0:2.4.3-44.el5",
            "python-tools-0:2.4.3-44.el5",
            "tkinter-0:2.4.3-44.el5",
            "python-0:2.6.6-20.el6",
            "python-debuginfo-0:2.6.6-20.el6",
            "python-devel-0:2.6.6-20.el6",
            "python-docs-0:2.6.6-2.el6",
            "python-libs-0:2.6.6-20.el6",
            "python-test-0:2.6.6-20.el6",
            "python-tools-0:2.6.6-20.el6",
            "tkinter-0:2.6.6-20.el6"
        ]
    },
    "references": [
        "http://bugs.python.org/issue6706",
        "http://bugs.python.org/issue9129",
        "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html",
        "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html",
        "http://secunia.com/advisories/43068",
        "http://secunia.com/advisories/50858",
        "http://secunia.com/advisories/51024",
        "http://secunia.com/advisories/51040",
        "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289",
        "http://svn.python.org/view?view=rev&revision=84289",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216",
        "http://www.openwall.com/lists/oss-security/2010/09/09/6",
        "http://www.openwall.com/lists/oss-security/2010/09/11/2",
        "http://www.openwall.com/lists/oss-security/2010/09/22/3",
        "http://www.openwall.com/lists/oss-security/2010/09/24/3",
        "http://www.securityfocus.com/bid/44533",
        "http://www.ubuntu.com/usn/USN-1596-1",
        "http://www.ubuntu.com/usn/USN-1613-1",
        "http://www.ubuntu.com/usn/USN-1613-2",
        "http://www.vupen.com/english/advisories/2011/0212",
        "https://bugs.launchpad.net/zodb/+bug/135108",
        "https://bugzilla.redhat.com/show_bug.cgi?id=632200",
        "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210"
    ],
    "refmap": {
        "bid": [
            "44533"
        ],
        "confirm": [
            "http://bugs.python.org/issue9129",
            "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289",
            "http://svn.python.org/view?view=rev&revision=84289",
            "https://bugzilla.redhat.com/show_bug.cgi?id=632200"
        ],
        "mandriva": [
            "MDVSA-2010:215",
            "MDVSA-2010:216"
        ],
        "misc": [
            "http://bugs.python.org/issue6706",
            "https://bugs.launchpad.net/zodb/+bug/135108"
        ],
        "mlist": [
            "[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
            "[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
            "[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
            "[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases"
        ],
        "secunia": [
            "43068",
            "50858",
            "51024",
            "51040"
        ],
        "suse": [
            "SUSE-SR:2010:024",
            "SUSE-SR:2011:002"
        ],
        "ubuntu": [
            "USN-1596-1",
            "USN-1613-1",
            "USN-1613-2"
        ],
        "vupen": [
            "ADV-2011-0212"
        ]
    },
    "summary": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [],
    "vulnerable_product": [
        "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*"
    ]
}